// src/pages/index.vue
<script lang="ts" setup>
import Slot from "@/components/Slot.vue";
import { useCookies } from "@vueuse/integrations/useCookies";

const cookies = useCookies(["slots"]);
const slots = cookies.get("slots");
if (!slots || slots.length !== 3) cookies.set("slots", [{}, {}, {}]);
</script>

<template>
  <main id="slots">
    <Slot
      v-for="(slot, index) in slots"
      :slot="slot"
      :index="index"
      :type="Object.entries(slot).length === 5 ? 'save' : 'slot'"
    />
  </main>

  <div>
    <pre>Slots ({{ slots.length === 0 ? false : true }}): {{ slots }}</pre>
    <br />
    <button
      @click="
        cookies.set('slots', [
          ...slots,
          {
            room: 143,
            gameTimer: 0,
            skillPoints: 0,
            explorationPoints: 0,
            progressPercentage: 0,
          },
        ])
      "
    >
      Push slot
    </button>
    <button @click="cookies.set('slots', [])">Reset slots</button>
  </div>
</template>

// pages/index.tsx
import { useEffect, useState } from "react";
import { Save } from "@components/Save";
import style from "@style/Slots.module.scss";

interface Slot {
  gameTimer: number;
  skillPoints: number;
  explorationPoints: number;
  progressPercentage: number;
}

export default function Slots() {
  const [slots, setSlots] = useState<Array<Partial<Slot>>>([{}, {}, {}]);
  useEffect(() => {
    try {
      // if (JSON.stringify(slots) !== localStorage.slots) {
      setSlots(JSON.parse(localStorage.slots));
      console.log("Fetched the slots successfully");
      console.log(localStorage.slots);
      // }
    } catch (error) {
      localStorage.slots = JSON.stringify(slots);
      console.log("Slots value was set to the initial value");
    }
  }, []);

  return (
    <main className={style.slots}>
      {slots.map((slot, index) => (
        <Save
          key={index}
          index={index}
          gameTimer={slot.gameTimer}
          skillPoints={slot.skillPoints}
          explorationPoints={slot.explorationPoints}
          progressPercentage={slot.progressPercentage}
          type={Object.keys(slots[index]).length === 0 ? "slot" : "save"}
        />
      ))}
    </main>
  );
}
