// src/pages/editor/[slot].vue
<script lang="ts" setup>
import * as levels from "~/lib/levels";
import Chapter from "@/components/Chapter.vue";

import { useStore } from "vuex";
import { useRoute } from "vue-router";
import { computed } from "@vue/reactivity";

const store = useStore();
const slots = computed(() => store.state.slots);

const route = useRoute();
const activeSlot = computed(() => slots.value[Number(route.params.slot)]);

if (!slots.value[Number(route.params.slot)]) location.href = "/"
</script>

<template>
  <header class="points">
    <div class="point-container">
      <h1>
        <input
          id="skill-points"
          min="0"
          max="244"
          type="number"
          maxlength="3"
          :value="activeSlot.skillPoints"
        />
        <label for="skill-points">/244</label>
      </h1>
      <img src="/img/difficulty-point.png" alt="Skill points" />
    </div>
    <div class="point-container">
      <h1>
        <input
          id="exploration-points"
          min="0"
          max="46"
          type="number"
          maxlength="2"
          :value="activeSlot.explorationPoints"
        />
        <label for="exploration-points">/46</label>
      </h1>
      <img src="/img/exploration-point.png" alt="Exploration points" />
    </div>
  </header>

  <main class="levels">
    <Chapter id="A" :levels="levels.ChapterA" />
    <Chapter id="B" :levels="levels.ChapterB" />
    <Chapter id="C" :levels="levels.ChapterC" />
    <Chapter id="D" :levels="levels.ChapterD" />
    <Chapter id="E" :levels="levels.ChapterE" />
    <Chapter id="Other" :levels="levels.OtherLevels" />
  </main>
</template>

// pages/slots/[slot].tsx
import { useRouter } from "next/router";
import { Chapter } from "@components/Chapter";
import style from "@styles/Levels.module.scss";

import ChapterA from "@lib/levels/chapter-a";
import ChapterB from "@lib/levels/chapter-b";
import ChapterC from "@lib/levels/chapter-c";
import ChapterD from "@lib/levels/chapter-d";
import ChapterE from "@lib/levels/chapter-e";

export default function Levels() {
  const router = useRouter();
  let activeSlot = { skillPoints: 0, explorationPoints: 0 };
  if (typeof window !== "undefined")
    activeSlot = JSON.parse(localStorage.slots)[Number(router.query.slot)];

  const skillPoints = activeSlot.skillPoints;
  const explorationPoints = activeSlot.explorationPoints;
  return (
    <>
      <header className={style.points}>
        <div>
          <h1>{skillPoints}/244</h1>
          <img
            src="/image/difficulty_point.png"
            alt="difficulty_point"
            title="Skill points"
          />
        </div>
        <div>
          <h1>{explorationPoints}/45</h1>
          <img
            src="/image/exploration_point.png"
            alt="exploration_point"
            title="Exploration points"
          />
        </div>
      </header>

      <main className={style.levels}>
        <Chapter id="A" levels={ChapterA} />
        <Chapter id="B" levels={ChapterB} />
        <Chapter id="C" levels={ChapterC} />
        <Chapter id="D" levels={ChapterD} />
        <Chapter id="E" levels={ChapterE} />
      </main>
    </>
  );
}
